@startuml
'https://plantuml.com/object-diagram
!pragma layout smetana
'made the 28/04/2025
object customer{
name
phoneNumber
E-mail
}
object salesPerson{
name
phoneNumber

}
object Order{
}
object billOfMaterials{
}
object Materials{
}


customer -- Order
Order -- billOfMaterials
Materials -- billOfMaterials
salesPerson -- Order




@enduml
